### ISSUE TITLE
Rafał's stem measurements.

### ISSUE THREAD

**Issue by typesupply** [typesupply/lasermeasure#16]
Would something like this be useful? https://github.com/RafalBuchner/StemThickness I haven't studied the code, but base on the video, the algorithm seems to be something like this:

```
if the cursor is near a contour:
  get the intersection point of the contour near the cursor.
  determine the angle at the contour at the intersection point.
  test for intersections perpendicular to that angle from the intersection point (with the cursor being collinear)
  report the first hit.
```

This would be useful for measuring diagonals and curves to check for monolinearity, etc.

---

This was suggested by @JakobFangmeier in #3.

**Comment by typesupply** [comment]
I forgot to cc @RafalBuchner. 😩 Thanks for this measurement idea, Rafał!

**Comment by typesupply** [comment]
Update on my thinking on this...

I want to add this, but it is a different type of measurement than what the tool currently displays. My current plan is to add require a modifier key in addition to the standard trigger key to toggle to this measurement type. That will require a bit of reworking inside of the display layer structure and event interpretation code, but it's not a huge change. I'll probably implement this in the next version.

**Comment by ryanbugden** [comment]
➕
I would LOVE this feature!

**Comment by typesupply** [comment]
Rafał built this as a separate extension. I use it. 😄 So, I'm closing this issue.
