### ISSUE TITLE
HUD looks cropped off

### ISSUE THREAD

**Issue by ryanbugden** [typesupply/lasermeasure#32]
<img width="219" alt="image" src="https://github.com/typesupply/lasermeasure/assets/12752088/a417a87b-6461-48f0-8be3-350f42dfad46">
Might just be me, but I'm getting this display.

**Comment by typesupply** [comment]
I've been getting this, too. It's driving me nuts.

**Comment by typesupply** [comment]
I just went to work on this and, _bizarrely_, it is working again without me changing anything. The only thing that I can think of is that I upgraded my OS to 13.4.

<img width="184" alt="image" src="https://github.com/typesupply/lasermeasure/assets/4992934/1f15ea35-b580-4aef-832b-d3adcde83ab3">

**Comment by ryanbugden** [comment]
Yeah, weirdly it's been working for me, too. Not sure what was causing it, because I'm still on 13.3.1. Can probably close the issue and reopen only if it * crops * up again.
