### ISSUE TITLE
Slowly fading measurements.

### ISSUE THREAD

**Issue by typesupply** [typesupply/lasermeasure#8]
Crazy idea: One of the annoying things is remembering values. What if I take advantage of Merz's the animation capabilities of `propertyGroup`, specifically `duration` and `animationFinishedCallback`, to make values fade. I could make it so that if hovering over a value for a certain time or pressing a modifier while measuring "locks" the text to be visible. It could then fade for a few seconds and the callback could remove it from the super layer when the opacity hits 0.

**Comment by ryanbugden** [comment]
Super cool! This might be related to another idea I was thinking about... An option to keep the measurement on while you make changes to the glyph.

Basically, one current limitation with RF’s native measurement tool is not being able to stay snapped to points of interest (e.g. measuring distance of two points—at an angle from one another—while moving the points.)
